name: Basic OIDC workflow

on: 
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  id-token: write  # required for OIDC
  contents: read    

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "First Step"
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-south-1
      
      - name: CDK diff (optional)
        run: npx cdk diff --all || true

      - name: CDK deploy
        run: npx cdk deploy --all $CDK_PARAMS          